name: tf-gic
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.11
  - pip
  - setuptools

  # Scientific computing
  - numpy
  - scipy
  - pandas
  - xarray
  - netcdf4
  - cftime

  # Geospatial
  - geopandas
  - shapely
  - cartopy
  - folium

  # Deep learning
  - pytorch

  # Visualisation
  - matplotlib-base
  - seaborn

  # Utilities
  - tqdm

  - pip:
    - bezpy==0.1.1
    - tfgic